name: Merge Check

on:
  pull_request:
    branches:
      - devel
      - stage
      - prod

jobs:
  check-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ "${{ github.base_ref }}" == "devel" ]]; then
            if [[ ! "${{ github.head_ref }}" =~ ^(feature|bugfix) ]]; then
              echo "Merging into devel branch is allowed only from feature or bugfix branches."
              exit 1
            fi
          elif [[ "${{ github.base_ref }}" == "stage" ]]; then
            if [[ "${{ github.head_ref }}" != "devel" ]]; then
              echo "Merging into stage branch is allowed only from devel branch."
              exit 1
            fi
          elif [[ "${{ github.base_ref }}" == "prod" ]]; then
            if [[ "${{ github.head_ref }}" != "stage" ]]; then
              echo "Merging into production branch is allowed only from stage branch."
              exit 1
            fi
          fi
